workflows:
  massapp_workflow:
    name: Build MassApp APK (Auto Generate Android Folder)
    environment:
      flutter: stable
    scripts:
      - flutter create .
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    working_directory: massapp_frontend
