workflows:
  massapp-release:
    name: MassApp Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        GOOGLE_SERVICES_JSON: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    scripts:
      # Step 1: Buat google-services.json dari Environment Variable
      - echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      # Step 2: Install dependencies
      - flutter pub get

      # Step 3: Build APK Release
      - flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - septian.j@gmail.com
