workflows:
  massapp-release:
    name: MassApp Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        GOOGLE_SERVICES_JSON: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    scripts:
      # Step 1: Pastikan google-services.json tersedia
      - mkdir -p android/app
      - echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      # Step 2: Clean cache untuk mencegah error dependency
      - rm -rf .dart_tool
      - flutter pub cache repair

      # Step 3: Install dependencies
      - flutter pub get

      # Step 4: Build APK Release
      - flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    working_directory: massapp_frontend

    publishing:
      email:
        recipients:
          - septian.j@gmail.com
