workflows:
  massapp_workflow:
    name: Build MassApp
    environment:
      flutter: stable
    scripts:
      - cd massapp_frontend
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - massapp_frontend/build/app/outputs/flutter-apk/app-release.apk
