// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTx2tjM_h3Hb0rmH3GUMl2QJPmJtwrPU4',
    appId: '1:566010385220:web:908881b8924da76e09bd11',
    messagingSenderId: '566010385220',
    projectId: 'massapp-b2727',
    authDomain: 'massapp-b2727.firebaseapp.com',
    storageBucket: 'massapp-b2727.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-5lwHy0-1v5vk8Sqsr0FUztksmKjvSDU',
    appId: '1:566010385220:android:2006be183e4ddda709bd11',
    messagingSenderId: '566010385220',
    projectId: 'massapp-b2727',
    storageBucket: 'massapp-b2727.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYmaqryOBbu50UhhGMCbaRNsZLCNWCoe4',
    appId: '1:566010385220:ios:95db3d462d42a2bd09bd11',
    messagingSenderId: '566010385220',
    projectId: 'massapp-b2727',
    storageBucket: 'massapp-b2727.firebasestorage.app',
    iosBundleId: 'com.example.massappFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYmaqryOBbu50UhhGMCbaRNsZLCNWCoe4',
    appId: '1:566010385220:ios:95db3d462d42a2bd09bd11',
    messagingSenderId: '566010385220',
    projectId: 'massapp-b2727',
    storageBucket: 'massapp-b2727.firebasestorage.app',
    iosBundleId: 'com.example.massappFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTx2tjM_h3Hb0rmH3GUMl2QJPmJtwrPU4',
    appId: '1:566010385220:web:70754208d29e2abd09bd11',
    messagingSenderId: '566010385220',
    projectId: 'massapp-b2727',
    authDomain: 'massapp-b2727.firebaseapp.com',
    storageBucket: 'massapp-b2727.firebasestorage.app',
  );
}
